### ISSUE TITLE
Harmoniser la liste

### ISSUE THREAD

**Issue by emchateau** [ouvroir/dahprojects#1]
La liste de références n’est pas toujours consistante. 
- [ ] Définir un niveau de description approprié
- [ ] Harmoniser la liste et

**Comment by LeaMaronet** [comment]
Pour harmonisation : 
- [ ] <biblFull> ou <biblStruct> ?
- [ ] xml:lang="fre" et non "fr" ? Pareil pour "eng" par "en" ?
- [ ] Quelle langue pour la description des projets ? Harmonisation des textes, traduction ? 
- [ ] Pour les sous-projets <biblStruct> est utilisé, conserver ? 
- [ ] Pour les sous-projets dans <analytic>, types dans <title> pas définis.

**Comment by emchateau** [comment]
- Tout passer en biblFull, sauf les références biblio dans le texte
 - xml:lang="fr" mais les deux sont compatibles
 - pour les descriptions, j’ai rapidement pris le parti de sélectionner un court résumé de présentation du projet tel qu’il apparaît sur le site. Dans un premier temps nous pouvons faire ça, donc dans la langue originale, et nous verrons après si nous souhaitons produire qqch de bilingue
 - conserver le biblStruct dans les références biblio sur les projets
 - pouvez-vous me citer une ligne, svp ? il est possible que cela soit un résidu d’un essai d’encodage ?

**Comment by LeaMaronet** [comment]
Merci ! 
J'ai plusieurs questions/propositions :
- Indiquer un "type" pour les notes ne serait-il pas pertinent ? Par exemple `type="abstract"` pour les notes résumant les projets et `type="projectBib"` pour celles bibliographiques ?
- Comment référencer les projets qui ont évolué/changé de nom ? Par exemple [Rome Reborn](http://romereborn.frischerconsulting.com) est devenu [Flyover Zone](https://www.flyoverzone.com/) ?
-

**Comment by LeaMaronet** [comment]
Merci !
J'ai plusieurs questions/propositions :

- Indiquer un "type" pour les notes ne serait-il pas pertinent ? Par exemple `type="abstract"` pour les notes résumant les projets et `type="projectBib"` pour celles bibliographiques ?
- Comment référencer les projets qui ont évolué/changé de nom ? Par exemple [Rome Reborn](http://romereborn.frischerconsulting.com/) est devenu [Flyover Zone](https://www.flyoverzone.com/) ? En ajoutant un élément `title type="old"` avec l'ancien titre du projet ?

**Comment by LeaMaronet** [comment]
@emchateau 
J'ai plusieurs questions/propositions :

- J'ai ajouté un "type" sur les balises `note` (par exemple `type="abstract"` pour les notes résumant les projets et `type="projectBib"` pour celles bibliographiques), est-ce-que cela vous convient ?
- Comment référencer les projets qui ont évolué/changé de nom ? Par exemple [Rome Reborn](http://romereborn.frischerconsulting.com/) est devenu [Flyover Zone](https://www.flyoverzone.com/) ? En ajoutant un élément `title type="old"` avec l'ancien titre du projet ?
- Comment indiquer les partenaires scientifiques d'un projet, qui ne sont ni ceux qui le financent ni ceux qui le publient ? Dans une balise `authority` ?

**Comment by emchateau** [comment]
- Utiliser @type 'biblio' plutôt que 'projectBib'
- Pour les reprise de projet faire un fiche différente
- Pour les partenaires @respStmt
