### ISSUE TITLE
Élaborer et modifier le schéma

### ISSUE THREAD

**Issue by LeaMaronet** [ouvroir/dahprojects#3]
Modifier l'ODD pour le projet de répertoire en HDA. (voir le modèle dans le header pour la description des sources MsDesc)
- [x] intégrer noteStmt et note
- [x] taxonomie
- [x] ajouter `<keywords>`dans le modèle de `<biblFull>`

**Comment by LeaMaronet** [comment]
J'ai inséré la taxonomie TaDiRAH dans le header du projet, avec une courte description de celle-ci. Je pensais ajouter une balise `<keywords scheme="#TaDiRAH">` composée de balises `term` après les notes sur chaque projet mais je me demande s'il ne serait pas plus pertinent d'ajouter les `keywords` dans une note spécifique ? Qu'en pensez-vous ? @emchateau

**Comment by emchateau** [comment]
Salut,

Comme je ne suis pas certain que nous devions déclarer tous les termes de Tadirah dans le fichier, je me demande si nous ne devrions pas plutôt déclarer une taxonomie avec classDecl > taxonomy puis y simplement faire référence aux identifiants génériques de la taxinomie avec catRef et @target https://tei-c.org/release/doc/tei-p5-doc/fr/html/ref-catRef.html <https://tei-c.org/release/doc/tei-p5-doc/fr/html/ref-catRef.html> Mais ce n’est vraiment pas très satisfaisant car c’est seulement disponible dans imprint

Ne devrions-nous pas poser la question sur la liste TEI ?
Salutations,
Emmanuel

**Comment by LeaMaronet** [comment]
@emchateau J'ai réalisé une première version de l'ODD, je l'ai rendu assez contraignant. Avant de continuer à travailler dessus, est-ce-que ce serait possible d'avoir votre avis dessus ? :) Je n'ai pas encore intégré les éléments associés à la taxonomie ou aux tags (j'attends de voir comment nous allons précisément utiliser TADIRAH)
